# Generated by Django 4.2.6 on 2023-12-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='username',
        ),
    ]
