# Generated by Django 4.2.6 on 2023-12-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_notes_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='note',
            new_name='notestb',
        ),
    ]
