# Generated by Django 4.2.6 on 2023-12-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_note_notestb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notestb',
        ),
    ]
