# Generated by Django 4.2.6 on 2023-12-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='note',
        ),
    ]
