# Generated by Django 4.2.6 on 2023-12-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_querydata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='querydata',
            new_name='note',
        ),
    ]
