# Generated by Django 4.2.6 on 2023-12-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_querydata_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='note',
        ),
    ]
