# Generated by Django 4.2.6 on 2023-12-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='another',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('query', models.CharField(max_length=100)),
                ('cate', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='Media')),
                ('comment', models.TextField()),
            ],
        ),
    ]
