# Generated by Django 4.2.6 on 2023-12-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_another'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('cate', models.CharField(max_length=100)),
                ('myfile', models.FileField(upload_to='Media')),
                ('comments', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='another',
        ),
    ]
