# Generated by Django 4.2.6 on 2023-12-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_data_delete_another'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
    ]
