# Generated by Django 4.2.6 on 2023-12-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='file',
            new_name='myfile',
        ),
    ]
