# Generated by Django 4.2.6 on 2023-12-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_file_notes_myfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notes',
            new_name='mynotes',
        ),
    ]
