# Generated by Django 4.2.6 on 2023-12-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_usersingup_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mynotes',
            name='myfile',
        ),
    ]
